### ISSUE TITLE
GGUF model support

### ISSUE THREAD

**Issue by TheBloke** [marella/ctransformers#102]
I'm creating this issue to discuss GGUF support in ctransformers.

I know you're planning to work on that soon, @marella .

I will be uploading my first GGUF models tonight.  In that README, I want to give users an idea of when the various clients and libraries will support GGUF, and link them to the issue/PR that is tracking support.

So I made this issue so I can link people to here.  When you have a rough idea of your ETA for ctransformers support, it would be great if you could post it here.  And ping me when it's live.

Thanks!

**Comment by TheBloke** [comment]
My first GGUF here if you want something to test with: https://huggingface.co/TheBloke/PuddleJumper-13B-GGUF

**Comment by willb0** [comment]
+1 would love this and can contribute if needed

**Comment by marella** [comment]
Thanks for uploading. I will release it today. I'm waiting for Falcon GGUF CUDA support (https://github.com/ggerganov/llama.cpp/pull/2760) to be merged so that I include that also in the release.

**Comment by marella** [comment]
Added GGUF format support for Llama and Falcon models in the latest version 0.2.24
I maintained backward compatibility, so existing GGML models will continue to work.
It also has the latest llama.cpp changes for Code Llama models.

**Comment by matthoffner** [comment]
Thank you @marella
