### ISSUE TITLE
'max_new_tokens' config not working for LLama2-7B chat

### ISSUE THREAD

**Issue by Revanth-guduru-balaji** [marella/ctransformers#104]
self.llama7b_Chat =  CTransformers(model="llama-2-7b-chat.ggmlv3.q4_0.bin",model_type="llama",gpu_layers=50)
self.llama7b_Chat.config={"max_new_tokens":4096}

question:
what is python programming language explain 

answer: Number of tokens generated 248
 Python is a high-level, interpreted programming language that is widely used for various purposes such as web development, scientific computing, data analysis, artificial intelligence, and more. Here are some key features of the Python programming language:

1. Syntax: Python's syntax is simple and easy to read, making it a great language for beginners. It uses indentation to define block-level structure, which helps in readability.
2. Object-oriented: Python is an object-oriented language, which means it supports concepts like encapsulation, inheritance, and polymorphism. This makes it easy to write reusable code and create modular programs.
3. Dynamic typing: Python is a dynamically-typed language, which means it does not require explicit type definitions for variables. Instead, the type of a variable is determined at runtime.
4. Extensive standard library: Python has an extensive standard library that includes modules for various tasks such as file I/O, networking, and data structures. This makes it easy to write code without having to reinvent the wheel.
5. Cross-platform: Python can run on multiple platforms, including Windows, macOS, and Linux. It can also be run in a web browser via

**Comment by marella** [comment]
You should pass config directly to `CTransformers` class:

```py
config = {"max_new_tokens": 4096}

llm = CTransformers(..., config=config)
```

See [LangChain docs](https://python.langchain.com/docs/integrations/providers/ctransformers).

**Comment by Revanth-guduru-balaji** [comment]
> You should pass config directly to `CTransformers` class:
> 
> ```python
> config = {"max_new_tokens": 4096}
> 
> llm = CTransformers(..., config=config)
> ```
> 
> See [LangChain docs](https://python.langchain.com/docs/integrations/providers/ctransformers).

Hi I wanted to play around config using sliders in streamlit every time it loads models freshly for the new config. Is there a way to load model once and change config.

**Comment by marella** [comment]
You can change using:

```py
llm.model.config.max_new_tokens = 4096
```

but it is a bit hacky.
