### ISSUE TITLE
LLM.generate ignores max_new_tokens config

### ISSUE THREAD

**Issue by rmc135** [marella/ctransformers#108]
If I generate with llm("...", max_new_tokens=10) then the output is as expected (up to, but never exceeding, 10 tokens)

_(edit: With a larger string as input, llm() also seems to ignore max_new_tokens, and keeps generating tokens, potentially until a crash. I haven't been able to nail down an exact number that it switches to generating without bounds, but for GPT2-XL it's somewhere around 456 to 471 input tokens, plus max_new_tokens between 8 and 20)_

However, if I set llm.config.max_new_tokens = 10 then use llm.tokenize() and llm.generate(), the config seems to be ignored, and a random number of tokens is output - often more than the default of 256. With a long enough input prompt it will crash with the error "not enough space in the context's memory pool", presumably because the total token count exceeds context size.

The same thing happens with both gpt2-xl and llama-7b

Is this behaviour valid and I'm doing something wrong (why does LLM.generate duplicate most of the config variables, but not max_new_tokens?), or is this a bug? Not a Python programmer, so maybe I'm doing something silly.

Sample code demonstrates the issue. Thanks!

```
from ctransformers import AutoModelForCausalLM

#llm = AutoModelForCausalLM.from_pretrained("/home/ai/gpt-2/models/1558M/ggml-model-f16.bin", model_type="gpt2", lib="avx2", local_files_only=True)
llm = AutoModelForCausalLM.from_pretrained("/home/ai/llama/models/7B/ggml-model-Q4_K_M.bin", model_type="llama", lib="avx2", local_files_only=True)

llm.config.max_new_tokens = 10
print(llm.config)

prompt_str = "Hi there,"

prompt_tokens = llm.tokenize(prompt_str)
output_tokens = llm.generate(prompt_tokens, top_k=10)
out_str = llm.detokenize(output_tokens)
print(out_str)
t = llm.tokenize(out_str)
print("output token count:", len(t))
```

Sample run showing excessive output tokens, not <=10, not <=256:

```
Config(top_k=40, top_p=0.95, temperature=0.8, repetition_penalty=1.1, last_n_tokens=64, seed=-1, batch_size=8, threads=-1, max_new_tokens=10, stop=None, stream=False, reset=True, context_length=-1, gpu_layers=0, mmap=True, mlock=False)
I have been playing the game for about 3 years now. I was introduced to this game through the first beta release by a friend who is a very nice person and a good player. Since then it has always been an interesting and entertaining experience, with lots of things to do. However, as the game is getting more popular, the number of people playing has increased. I am currently a Level 5 (Level 4 before that was a level 1) and have been playing for about 2 months. I've also had my friend join in for the last 2 weeks as he wanted to help out his brother in game. He has played this game for over 2 years, so it is only natural for him to play. I would say that the game is pretty balanced and there are no real overpowered items in it at the moment (unless you want to consider some of the more recent patches). There have been times where I've had a bad run and had to restart the game, but this has never happened with my friend. So basically what you will experience playing in an active role on the team is that you are constantly having to deal with your teammates' actions.

The only problem I have found with the game is that it can be very difficult to find a good balance between being a support and a carry. If you want to play as a support, you will need to be able to keep up with your teammates, and also make sure they are doing well in lane. This is where your items come into play, since your support role has the least amount of damage. Therefore you will need to have some form of healing items such as potions or health pots to keep your carry in tip-top condition during lane phases and also help him survive a few extra hits. If you want to be a carry, you will need to make sure you can outdamage the enemy carry (and if you are a support, you will need to be able to keep up with your teammates). This means having the proper item setup that makes sure that you have enough damage to kill the enemy carry and also enough health to survive.

I would say that I like playing support, since I get to help my team out by being the healer, but I don't really enjoy playing as a carry. The only reason I play as a carry is because it's easier for me to do than a support role. I feel like if I were to play as a support, I would have to be more focused on the lane and make sure that my team is doing well in it, which would make the game more boring and less enjoyable for me.

I hope this helps some of you out there who are looking for a new game to try out. If you have any questions or comments, feel free to leave them below.
output token count: 567
```

**Comment by marella** [comment]
`llm.generate` is a low level function which doesn't use `max_new_tokens`. You can restrict it using:

```py
output_tokens = []
for token in llm.generate(...):
    output_tokens.append(token)
    if len(output_tokens) > max_new_tokens:
        break
```

Any reason why you are using this instead of calling `llm(prompt)` directly?

**Comment by rmc135** [comment]
Thanks for the response. See the edit of the OP (second para in italics), the same error also happens when using llm(prompt) once the prompt size exceeds around 450ish tokens.

It looks like the error is caused by insufficient memory allocation of GGML, but I am unsure why ctransformers seems to crash with a lower number of tokens (GGML dies at 825 with same model). See https://github.com/ggerganov/ggml/issues/480

Here's some code which crashes every time with a prompt size of 448 tokens. If you remove the last word from prompt_str, making the input size 445 tokens, it will generate without crashing.

```from ctransformers import AutoModelForCausalLM

llm = AutoModelForCausalLM.from_pretrained("/home/ai/gpt-2/models/1558M/ggml-model-f16.bin", model_type="gpt2", lib="avx2", local_files_only=True)

prompt_str = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing"

t = llm.tokenize(prompt_str)
print("prompt token count:", len(t))
out_str = llm(prompt_str, max_new_tokens=10)
print(out_str)
t = llm.tokenize(out_str)
print("output token count:", len(t))
```

```
$ python -V
Python 3.10.12
$ python test_github_issue.py
prompt token count: 448
ggml_new_object: not enough space in the context's memory pool (needed 268627040, available 268435456)
Segmentation fault (core dumped)

...(edit source to trim prompt_str)...

$ python test_github_issue.py
prompt token count: 445
 adipiscing elit, sed do eius
output token count: 10
```

**Comment by marella** [comment]
Try reducing the batch_size (default is 8):

```py
llm(..., batch_size=1)
```

> It looks like the error is caused by insufficient memory allocation of GGML, but I am unsure why ctransformers seems to crash with a lower number of tokens (GGML dies at 825 with same model). See https://github.com/ggerganov/ggml/issues/480

In the ggml example, it looks like you are generating 825 tokens (`-n 825` means `max_new_tokens=825`) not passing 825 tokens as input. Are you using the same prompt for both?

**Comment by rmc135** [comment]
> > It looks like the error is caused by insufficient memory allocation of GGML, but I am unsure why ctransformers seems to crash with a lower number of tokens (GGML dies at 825 with same model). See [ggerganov/ggml#480](https://github.com/ggerganov/ggml/issues/480)
> 
> In the ggml example, it looks like you are generating 825 tokens (`-n 825` means `max_new_tokens=825`) not passing 825 tokens as input. Are you using the same prompt for both?

Yes, converted an API daemon written for HuggingFace transformers into ctransformers (which is why I was originally using separate tokenization). To try to replicate the problem, I then passed to ggml directly (eg ```bin/gpt-2 -m ... -p ...```) the exact same prompts that caused a segfault under the Python+ctransformers code.

Investigating further, it seems that ggml is also the reason for endless generation. The same prompt from the example Python code above ignores the -n parameter and just continues generating until it runs out of memory. For example, ```bin/gpt-2 -m /home/ai/gpt-2/models/1558M/ggml-model-f16.bin -p <above_prompt> -n 10``` generates about as much new text as the prompt (a few hundred tokens!)

So we have 2 problems here, likely not really directly related to ctransformers:

1. Insufficient memory allocation for full context length of GPT-2 model causes generation to crash at around 825 total tokens
2. Some bug which ignores ```-n ...``` (ggml) / max_new_tokens (ctransformers) if the prompt is long enough - but ONLY if it's past a certain length - generating without bounds until memory is exceeded as per problem 1. If the prompt is shorter, generated output is limited to <=max_new_tokens as expected.

I will flag this to the ggml team, and will try your per-token suggestion in the meantime.

**Comment by rmc135** [comment]
Hi again!

GGML subsequently updated the allocation code which I guess fixes problem 1 in the last comment: https://github.com/ggerganov/ggml/pull/486

I've upgraded ctransformers but it's unclear whether this change has been merged? Still segfaults with my sample code in https://github.com/marella/ctransformers/issues/108#issuecomment-1694677504
