### ISSUE TITLE
A way to unload a model?

### ISSUE THREAD

**Issue by Remowylliams** [marella/ctransformers#111]
Hi There,
   I'm using ctransformers with Oobabooga text-generation-webui and I can load models fine. All the other loaders let me load, unload, reload models at will. When I load a model with ctransformers as stated it works fine but using the unload button does nothing, and if I try to load another model it loads it ontop of the model already in vram usually causing an OOM vram cuda failure. 
  I looked through your code a bit and didn't find any interface for requesting an unload of a model. Is this something that can be implimented? Or if it is, can you tell me how to make it happen?

Many Thanks.
Remo

**Comment by marella** [comment]
Hi, https://github.com/oobabooga/text-generation-webui/pull/3711 should fix it.

**Comment by yashpundir** [comment]
Hey, is there a way to unload the model via the CTransformers library itself.

**Comment by yashpundir** [comment]
How can we unload using CTransformers itself? I'm not using any other library on top of CTransformers or Web GUI as such.
