### ISSUE TITLE
using ctransfromers for langchain agents pnadas data frame agent

### ISSUE THREAD

**Issue by deepthi97midasala** [marella/ctransformers#119]
from langchain.llms import CTransformers
from ctransformers import AutoModelForCausalLM

llm = AutoModelForCausalLM.from_pretrained('TheBloke/Llama-2-7B-Chat-GGML', model_file = 'llama-2-7b-chat.ggmlv3.q4_K_S.bin' )

agent = create_pandas_dataframe_agent(llm,df,verbose=True)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
[<ipython-input-12-0d7178d40fea>](https://localhost:8080/#) in <cell line: 1>()
----> 1 agent = create_pandas_dataframe_agent(llm,df,verbose=True)

2 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py](https://localhost:8080/#) in __init__(__pydantic_self__, **data)
    339         values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340         if validation_error:
--> 341             raise validation_error
    342         try:
    343             object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for LLMChain
llm
  value is not a valid dict (type=type_error.dict)

**Comment by marella** [comment]
In LangChain, you shouldn't use `AutoModelForCausalLM.from_pretrained`. You should use `CTransformers` class to create llm object:

```py
from langchain.llms import CTransformers

llm = CTransformers(model='TheBloke/Llama-2-7B-Chat-GGML', model_file='llama-2-7b-chat.ggmlv3.q4_K_S.bin')
```

See [LangChain docs](https://python.langchain.com/docs/ecosystem/integrations/ctransformers).

**Comment by deepthi97midasala** [comment]
Thank you sir i want to know that is llama2 good to use pandas dataframe
agent, if possible provide me good source for it
