### ISSUE TITLE
CUDA library without AVX2, FMA, F16C support possible?

### ISSUE THREAD

**Issue by m-from-space** [marella/ctransformers#120]
I have an older CPU that doesn't support AVX2, FMA and F16C. But I have an RTX with CUDA support.

For `llama-cpp-python` I was able to built CUDA support the following way:

`CMAKE_ARGS="-DLLAMA_CUBLAS=ON -DLLAMA_AVX2=OFF -DLLAMA_F16C=OFF -DLLAMA_FMA=OFF" FORCE_CMAKE=1 pip install llama-cpp-python`

Is it possible to install `ctransformers` the same way, so that I can load a model with CUDA? Doing this right now using `lib="cuda"` results in a segmentation fault (because the CPU cannot execute the instruction).

**Comment by m-from-space** [comment]
So I figured it out. The correct way to install it for me is:

`CT_CUBLAS=1 CT_INSTRUCTIONS=avx pip install ctransformers[cuda] --no-binary ctransformers --force-reinstall --upgrade`

**Comment by marella** [comment]
Above command installs from source and uses local CUDA libraries, so you can remove `[cuda]`:

```sh
CT_CUBLAS=1 CT_INSTRUCTIONS=avx pip install ctransformers --no-binary ctransformers
```
