### ISSUE TITLE
Batching support

### ISSUE THREAD

**Issue by NeonBohdan** [marella/ctransformers#14]
Looks like ggml supports batching 
Can it be supported here too
Will it gain some performance?

**Comment by marella** [comment]
Batching is already supported with the `batch_size` parameter (see [docs](https://github.com/marella/ctransformers#config)):

```py
llm(prompt, batch_size=8)
```

Batching is only used for evaluating prompt, so it can improve performance for large prompts but consumes more memory.

**Comment by NeonBohdan** [comment]
Thanks 
I saw that batching multiple prompts isn't supported by ggml yeat
Only for llama.cpp

**Comment by jstzwj** [comment]
The name of batch_size here may mislead the user. At first I was very confused about this parameter. I thought the parameter of batch_size means that multiple sentences can be inferred at the same time to get the result in one inference. But actually I read the code and found that batch_size refers to the number of tokens read in one step decoding.

**Comment by tikikun** [comment]
batch_size here is not correctly used term

**Comment by marella** [comment]
I will update the README to clarify it is for evaluating tokens in a single prompt.

**Comment by jacklxc** [comment]
More clarification is helpful. Even with the updated README, I was still confused.
