### ISSUE TITLE
ctx limiter.

### ISSUE THREAD

**Issue by miguelamendez** [marella/ctransformers#16]
Hi I have notice that there is no option to define the context amount (max tokens) used for generation. Is the library using the maximum context by default?.

**Comment by marella** [comment]
Hi, currently it is using the context length defined in model file.

I just added an option to specify `context_length` for LLaMA models in the latest version 0.2.2:

```py
llm = AutoModelForCausalLM.from_pretrained(..., context_length=512)
```

Soon I will add it for other models.

**Comment by miguelamendez** [comment]
Thanks for the response, I'm using some mpt models but I'll check the files.

**Comment by marella** [comment]
For MPT, currently there is a hard limit of 4096 as the storywriter model requires lot of memory https://github.com/ggerganov/ggml/pull/165#issuecomment-1556233670
But I will soon allow changing it via `context_length` parameter.
