### ISSUE TITLE
Error when running ctransformers - std::runtime_Error

### ISSUE THREAD

**Issue by gab-luz** [marella/ctransformers#18]
Hi, folks. Here's the code I'm using:

```
from ctransformers import AutoModelForCausalLM

llm = AutoModelForCausalLM.from_pretrained('/mnt/mydisk/AI/text/models/llama_cpp/gpt4all-lora-quantized-ggml.bin', model_type='llama', gpu_layers=2,  lib='avx') # I've also tried without lib='avx'

print(llm('AI is going to'))
```

Here's the error I'm getting:
```

terminate called after throwing an instance of 'std::runtime_error'
  what():  unexpectedly reached end of file
```

What can I do?
Also, Koboldcpp works fine.

**Comment by marella** [comment]
Hi, can you please provide a link to download the model.

Have you tried it with [llama.cpp](https://github.com/ggerganov/llama.cpp) and see if it works.

**Comment by gab-luz** [comment]
I'll close it. It looks like some models are not running but when I update them up to ggjt3 or something like that, they seem to work.
