### ISSUE TITLE
Model crashes when tokenizing 4 digit numbers

### ISSUE THREAD

**Issue by underwaterbepis** [marella/ctransformers#22]
model.tokenize("1111")

crashes the python interpreter

if relevant, I'm using https://huggingface.co/TheBloke/Nous-Hermes-13B-GGML

**Comment by marella** [comment]
I pushed a fix. Will release it in the next version. If you would like to try it before the next release, you can install from source:

```sh
pip install git+https://github.com/marella/ctransformers
```

**Comment by marella** [comment]
This is fixed in the latest version 0.2.9
