### ISSUE TITLE
Ukrainian Upper case not appearing

### ISSUE THREAD

**Issue by Theodotus1243** [marella/ctransformers#23]
@marella thanks, very usefull project 
I use llama ggml model
With latest `llama.cpp` it says `Привіт`, but with ctransformers only `ривіт`
It is related to all words, not only first in a responce. `Банан` -> `анан`

I'm not sure if it's related to encoding or something else

**Comment by marella** [comment]
Can you please provide a prompt and if possible seed to reproduce the output.

**Comment by Theodotus1243** [comment]
Thanks
Here is the [demo](https://huggingface.co/spaces/theodotus/pythia-uk)
You can clone and run it

prompt `"<human>: Привіт\n<bot>:"`
Got `оброго дня` instead of `Доброго дня`

**Comment by Theodotus1243** [comment]
In `llama.cpp` no such problems
Also I looked in more detail about how it works 

It appeared that upper latters are represented as sequence of two tokens `<0xD0><0x91>` = `Б` for example

Maybe it's somehow related

**Comment by Theodotus1243** [comment]
Important note, I'm using `openllama`
But still it works with `llama.cpp`

**Comment by marella** [comment]
> It appeared that upper latters are represented as sequence of two tokens `<0xD0><0x91>` = `Б` for example

Thanks, this helped debug the issue. In UTF-8 encoding, some characters are encoded using multiple bytes and if those bytes are part of different tokens instead of one token, I was not decoding them properly.

I pushed a fix. Will release it in the next version. Can you please try installing from source and see if it works:

```sh
pip install git+https://github.com/marella/ctransformers
```

**Comment by Theodotus1243** [comment]
Thanks, it's solved issue
