### ISSUE TITLE
Redestribute cuda compatible version without the need to recompile locally

### ISSUE THREAD

**Issue by ParisNeo** [marella/ctransformers#25]
Hi and thanks for GPU integration. I made it work and that's cool.

But it requires the user to have cuda and all build tools installed with the specific version 11.7 (latest one supported by torch as of now), which makes the whole thing non user friendly.

I was thinking of precompiling this for many possible architectures then redestributing them.

**Comment by marella** [comment]
Hi, ctransformers should work with any CUDA version 11.7, 11.8, 12.1 it is not dependent on torch.
Are there any specific issues users are facing while building from source?

Also latest CUDA version supported by torch is 11.8 (it also supports 11.7)
I'm actually waiting for torch to add support for 12.1 (even though ctransformers is not dependent on torch) to provide precompiled libs for 12.1 (assuming most users will be using 12.1 once torch upgrades).

**Comment by ParisNeo** [comment]
Hi. I compared ctransformers with GPU vs llamacpp-python and it seems that llamacpp-python is faster. At least between generations, it seems that the generation has lower overhead. do you free up memory for each generation? this can lead to high latency when the generation starts.

**Comment by marella** [comment]
Hi, are you calling it by passing previous conversations for every generation to make it remember history? If so, it is better to use `reset: False` (default is `True`) and only pass new messages:

```py
llm = AutoModelForCausalLM.from_pretrained(..., reset=False)
response = llm(new_message)
```

To forget history, you can call:

```py
llm.reset()
```

**Comment by ParisNeo** [comment]
Hi and thanks.
I need to forget history at each step as my code regenerates the context with conditionning rework and a sliding window in the discussion. So I do llm.reset() for each generation. Is that freeing all the memory and starting fresh? I need to keep every thing loaded except the input so theoretically, it shouldn't be a problem.

**Comment by marella** [comment]
`llm.reset()` shouldn't be expensive as it only clears a small amount of memory.

Can you please try increasing the `batch_size`. In ctransformers default value is 8 but in llamacpp-python it appears to be 512.

```py
llm = AutoModelForCausalLM.from_pretrained(..., batch_size=?)
```

Larger `batch_size` will process the prompt faster but will require more memory.

Also if you have enough GPU memory to fit the model, setting `threads=1` can improve performance.

```py
llm = AutoModelForCausalLM.from_pretrained(..., threads=1)
```

**Comment by rodgermoore** [comment]
> Hi and thanks for GPU integration. I made it work and that's cool.
> 
> But it requires the user to have cuda and all build tools installed with the specific version 11.7 (latest one supported by torch as of now), which makes the whole thing non user friendly.
> 
> I was thinking of precompiling this for many possible architectures then redestributing them.

This would be great, I was struggling to get this to work in a Nvidia Docker container. Your comment about needing CUDA build tools saved my day as I was using the runtime image, not the dev image. Here is my Dockerfile:

```
# NVidia development base image
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

# Install necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# Create a user named "user"
RUN useradd -m user

# Switch to the new user
USER user

# Set the home directory for the new user
ENV HOME=/home/user
RUN mkdir -p $HOME/.local/bin
ENV PATH=$HOME/.local/bin:$PATH
ENV CT_CUBLAS=1

# Install the wheel file
WORKDIR $HOME/app
RUN pip install --user --no-cache-dir --upgrade pip && pip install --user --no-cache-dir notebook ipywidgets
RUN CT_CUBLAS=1 pip install --no-cache-dir ctransformers --no-binary ctransformers --user

# Set the working directory
WORKDIR $HOME/app

COPY start_services /start_services
CMD /start_services
EXPOSE 8888
``` 

This is my compose file to run the container:

```
version: '3'
services:
  ctransfomers:
    container_name: ctransfomers_cuda
    image: ctransformers:dev
    ports:
      - "8888:8888"
    volumes:
      - /models/ggml_models:/home/user/app/models
      - ./files:/home/user/app/files
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    runtime: nvidia
``` 

Running this code in Jupyter notebook (http://localhost:8888 after running docker compose up -d) now uses GPU :)

```
from ctransformers import AutoModelForCausalLM
llm = AutoModelForCausalLM.from_pretrained("TheBloke/LLaMa-7B-GGML", gpu_layers=50, threads=1)
print(llm('AI is going to'))
``` 
🎉

**Comment by marella** [comment]
In the latest version 0.2.21, precompiled libraries are provided for CUDA 12, so no compilation is required and it no longer needs CUDA to be installed at system level:

```sh
pip install ctransformers ctransformers[cuda]
```

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-7B-GGML", gpu_layers=50)
```

See [example](https://colab.research.google.com/drive/1Ihn7iPCYiqlTotpkqa1tOhUIpJBrJ1Tp) in Colab.

Feel free to re-open if you are still facing an issue.
