### ISSUE TITLE
Text output

### ISSUE THREAD

**Issue by vmajor** [marella/ctransformers#29]
I am back to testing ctransformers, now with the quantized mpt-30b-instruct model and I have a really basic problem. Does ctransformers handle output in a different way to transformers?

I have been trying for a while to get it to print a block of text, but when using the native huggingface tokenizer I either get a streaming output from the for loop where each decoded token is placed in new line, or I get a list:
```
python mpt-30b_transformers_test.py
['Blue', ' can', ' be', ' associated', ' with', ' many', ' things', ',', ' such', ' as', ' sadness', ' or', ' depression', ' due', ' to', ' its', ' association', ' in', ' mood', 's', ' and', ' feelings', ';', ' however', ' it', '’', 's', ' also', ' been', ' proven', ' through', ' research', ' studies', ' conducted', ' by', ' psychologists', ' at', ' Harvard', ' University', ' that', ' looking', '/', 'sur', 'round', 'ing', ' yourself', ' within', ' this', ' shade', ' will', ' reduce', ' your', ' stress', ' levels', '.', '  ', 'It', ' is', ' a', ' very', ' cal', 'ming', ' colour', ' which', ' makes', ' sense', ' when', ' you', ' think', ' about', ' the', ' sky', ',', ' sea', ' etc', ' where', ' blue', ' dominates', ' as', ' these', ' are', ' places', ' we', ' often', ' go', ' to', ' relax', ' and', ' switch', ' off', ' from', ' our', ' busy', ' lives', '!']
```
I can wrangle this into text, but it is an extra step and a bit of a pita as not every token is a word or a free syntax symbol so I am wondering if there is a better way to get plain text output when using ctransformers with a HF tokenizer.

**Comment by marella** [comment]
Can you please share the code you are using.

**Comment by vmajor** [comment]
I do not actually have a working example as I neglected to save revisions, but I narrowed down the issue to me not knowing what I am doing, and ctransformers.generate() outputting a list that is not in the same format as transformers.generate(). I therefore cannot just do this for example: 

```
python mpt-30b_transformers_test.py
Traceback (most recent call last):
  File "/home/*****/transformers/mpt-30b_transformers_test.py", line 35, in <module>
    print(tokenizer.decode(output_text[0]))
TypeError: 'generator' object is not subscriptable
```

The only way that I can get the output I can use with minimal effort is if I do not use the HF tokenizer. The main reason why I find this an issue is because I cannot just drop in ctransformers in place of transformers and carry on with the other parts of the code. without having to make any other changes.

**Comment by marella** [comment]
A generator object is an efficient way to create a list. You can convert generator object to list using `list()`:

```py
from ctransformers import AutoModelForCausalLM
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("marella/gpt-2-ggml")

inputs = tokenizer.encode(prompt)
outputs = model.generate(inputs)
outputs = list(outputs) # convert generator object to list
text = tokenizer.decode(outputs)
```

If you have a list of decoded tokens as you mentioned in the initial post, you can just do `"".join(decoded_tokens)`
