### ISSUE TITLE
Outputting text sentence by sentence

### ISSUE THREAD

**Issue by Eddy-Arch** [marella/ctransformers#33]
I was wondering if it would be possible to run inference and recieve the output line by line, instead of all at once
or as "mangled tokens"

**Comment by marella** [comment]
You can get it token by token by setting the `stream` parameter:

```py
for text in llm(prompt, stream=True):
  print(text, end="", flush=True)
```

**Comment by Eddy-Arch** [comment]
so thats how youre supposed to use the stream flag... my bad
