### ISSUE TITLE
ggml_new_tensor_impl: not enough space in the scratch memory pool 

### ISSUE THREAD

**Issue by vmajor** [marella/ctransformers#34]
I have a real bug this time.

```
ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 575702016, available 268435456)
Segmentation fault
```

This affects ggml implementation in llama.cpp so it is likely not a bug with ctransformers but an inherited bug from the ggml code. This appears on the second run, which to me means that there is a memory leak - the buffer is either not correctly sized and/or it is not cleared upon exit

**Comment by marella** [comment]
Can you please provide the code or steps to reproduce this error. Also please mention the model and parameters you are using.

**Comment by vmajor** [comment]
Thank you for a quick reply...and again it is not an actual bug. I had mistakenly set the batch size to a very high number (2048) which caused the scratch memory pool error.
