### ISSUE TITLE
Segfault when trying to use __call__ multiple times

### ISSUE THREAD

**Issue by abacaj** [marella/ctransformers#38]
Hi I was running this in a fastapi server generating text multiple times from the endpoint I end up getting segfault if I try to generate text before the previous generation has finished.

I am calling the llm directly:
```
llm("prompt goes here")
```

Tried a few models, streaming true + false, behavior seems to be the same. Have to wait for each generation to finish before trying to generate for other requests. Curious if this is expected behavior

**Comment by abacaj** [comment]
Closing this for now, appears to be related to ggml

**Comment by marella** [comment]
Hi, ggml models are not thread safe so making concurrent calls for generation will result in errors. So you should use a lock to prevent concurrent calls.
Another way would be to load multiple instances of model but it will consume lot more memory. Also making multiple calls at the same time would slow down the generation as each call has to compete for the CPU threads.
