### ISSUE TITLE
How to enable CTransformers load model_file from Google Drive?

### ISSUE THREAD

**Issue by pendekarcode** [marella/ctransformers#42]
I'm using from langchain.llms import CTransformers

I found error
ValidationError: 1 validation error for CTransformers
not found in '/root/.cache/huggingface/hub/
![Screenshot 2023-06-29 00 45 15](https://github.com/marella/ctransformers/assets/52091445/ad727835-48d4-4370-905e-56681aec2a26)

**Comment by marella** [comment]
You can directly pass the model file path using `model` parameter:

```py
llm = CTransformers(model=mpath, model_type="falcon", ...)
```

No need to specify `model_file` here.
