### ISSUE TITLE
Exllama support?

### ISSUE THREAD

**Issue by ParisNeo** [marella/ctransformers#47]
Hi,
exllama now can support 4k context size. Is that something you are planning on supporting in future version?

**Comment by marella** [comment]
Hi, added experimental support for GPTQ models using ExLlama in the latest version 0.2.18

Install dependencies using:

```sh
pip install ctransformers ctransformers[gptq]
```

To use a GPTQ model, set `model_type="gptq"`. If model path or name already has the word `gptq` then `model_type` is not required:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-7B-GPTQ")
```

See [Colab example](https://colab.research.google.com/drive/1SzHslJ4CiycMOgrppqecj4VYCWFnyrN0). LangChain integration also works.

Low-level APIs are not fully supported. I noticed that in LoLLMs you are using `model.generate()` [here](https://github.com/ParisNeo/lollms_bindings_zoo/blob/4dc26dd82609fd4540aff956c450c01b393c78db/c_transformers/__init__.py#L254-L277) which can be replaced with the stream API which is much simpler:

```py
for word in model(prompt, stream=True, max_new_tokens=n_predict, ...):
    ...
```

**Comment by ParisNeo** [comment]
cool. I'll give it a shot

**Comment by ParisNeo** [comment]
Here is the ctransformers binding generation function in lollms.

```python
def generate(self, 
                 prompt:str,                  
                 n_predict: int = 128,
                 callback: Callable[[str], None] = bool,
                 verbose: bool = False,
                 **gpt_params ):
        """Generates text out of a prompt

        Args:
            prompt (str): The prompt to use for generation
            n_predict (int, optional): Number of tokens to predict. Defaults to 128.
            callback (Callable[[str], None], optional): A callback function that is called every time a new text element is generated. Defaults to None.
            verbose (bool, optional): If true, the code will spit many information about the generation process. Defaults to False.
            **gpt_params: Additional parameters for GPT generation.
                temperature (float, optional): Controls the randomness of the generated text. Higher values (e.g., 1.0) make the output more random, while lower values (e.g., 0.2) make it more deterministic. Defaults to 0.7 if not provided.
                top_k (int, optional): Controls the diversity of the generated text by limiting the number of possible next tokens to consider. Defaults to 0 (no limit) if not provided.
                top_p (float, optional): Controls the diversity of the generated text by truncating the least likely tokens whose cumulative probability exceeds `top_p`. Defaults to 0.0 (no truncation) if not provided.
                repeat_penalty (float, optional): Adjusts the penalty for repeating tokens in the generated text. Higher values (e.g., 2.0) make the model less likely to repeat tokens. Defaults to 1.0 if not provided.

        Returns:
            str: The generated text based on the prompt
        """
        default_params = {
            'temperature': self.config.temperature,
            'top_k': self.config.top_k,
            'top_p': self.config.top_p,
            'repeat_penalty': self.config.repeat_penalty,
            'last_n_tokens' : self.config.repeat_last_n,
            "seed":self.binding_config.seed,
            "n_threads":self.binding_config.n_threads,
            "batch_size":self.binding_config.batch_size
        }
        gpt_params = {**default_params, **gpt_params}
        if gpt_params['seed']!=-1:
            self.seed = self.binding_config.seed
        try:
            output = ""
            self.model.reset()
            tokens = self.model.tokenize(prompt)
            count = 0
            for tok in self.model.generate(
                                            tokens,
                                            top_k=gpt_params['top_k'],
                                            top_p=gpt_params['top_p'],
                                            temperature=gpt_params['temperature'],
                                            repetition_penalty=gpt_params['repeat_penalty'],
                                            last_n_tokens=gpt_params['last_n_tokens'],
                                            seed=gpt_params['seed'],
                                            threads = gpt_params['n_threads'],
                                            batch_size= gpt_params['batch_size'],
                                            reset=True,
                                           ):
                
                if count >= n_predict or self.model.is_eos_token(tok):
                    break
                word = self.model.detokenize(tok)
                if callback is not None:
                    if not callback(word, MSG_TYPE.MSG_TYPE_CHUNK):
                        break
                output += word
                count += 1
                
                
        except Exception as ex:
            print(ex)
        return output       
```

I think you can take a look at the entire binding class. It is very easy to code and add options. I can follow advances in the bindings but I mostly want to concentrate on the applicative part of the tool and I think those who build the code layers can better help make the binding.


I think it could be a good thing if you take a look at it and give some advices or better, make a pullrequest and suggest upgrades. I'll be happy to accept them:

https://github.com/ParisNeo/lollms_bindings_zoo

Also the app itself is here:
https://github.com/ParisNeo/lollms-webui

 

Also I want to retribute the people who help making lollms the good tool it is, so I was thinking of adding your patreon link if you have one for your binding card:
![image](https://github.com/marella/ctransformers/assets/827993/e9054eeb-b102-492a-99da-b5136a402145)
I have already done this for the model providers:
![image](https://github.com/marella/ctransformers/assets/827993/63066b3c-1d6b-4c4b-a1cc-07338cf6bd22)

The binding has ui modifiable configuration that is very easy to modify in the code to add new options:
![image](https://github.com/marella/ctransformers/assets/827993/4a1f0f1f-415a-4579-b8fe-bd8bc34706d3)

The CTransformers can become my favorite for all cases if it didn't have this overhead loading time at the beginning of each generation. The exllama binding (that uses GPTQ models) is the fastest with GPU as of today.

But I admire your work, man. It is a pleasure to use this in lollms. If I can help promoting your work I won't hesitate.
