### ISSUE TITLE
Performance on Apple silicon

### ISSUE THREAD

**Issue by marella** [marella/ctransformers#5]
Context: https://github.com/marella/ctransformers/issues/1#issuecomment-1556068861

@bgonzalezfractal did you notice any performance improvement just by changing the `threads` parameter?

If you don't have the latest quantized models, you can go back to the previous commit using:

```sh
git checkout e707f99
git submodule update
```

Here you can run the build commands and check:

```sh
cmake -S . -B build
cmake --build build
```

**Comment by bgonzalezfractal** [comment]
@marella I haven't been able to use the llm again, once we manage to solve the starcoder quantize issue, I can post the M1 Pro 64GB performance.

**Comment by marella** [comment]
Hi, I'm guessing the issue might be related to performance - it is running too slow so taking time to print the output.

By default `print(llm(...))` function doesn't show any output until all the text is generated. So you can try the new `stream` option to see text as soon as a token is generated:

```py
for token in llm('def fibo(', max_new_tokens=5, stream=True):
    print(token, end='', flush=True)
```

---

The code used by starcoder example and this library is same. The only difference is in the way it is built. So building the library from source can help validate if building locally improves performance and may help the library from being stuck:

```sh
git clone --recurse-submodules https://github.com/marella/ctransformers
cd ctransformers

cmake -S . -B build
cmake --build build
```

```py
llm = AutoModelForCausalLM.from_pretrained(..., lib='/path/to/ctransformers/build/lib/libctransformers.dylib')
```
