### ISSUE TITLE
Feature request: support for Huggingface Hub branches/revisions

### ISSUE THREAD

**Issue by TheBloke** [marella/ctransformers#51]
I recently updated my Falcon GGMLs to the new GGCC format. But I kept the old ggml format models available in another branch, called `ggmlv3`

With Hugging Face Hub, it would be possible to download those like so:
```
model = AutoModelForCausalLM.from_pretrained("TheBloke/blah", revision="ggmlv3", ...)
```

My request is for the same to be supported in ctransformers, so branches can be used to differentiate between versions of models.

Thanks in advance.

**Comment by TheBloke** [comment]
Actually I just realised you're wrapping snapshot_download - so it would work if I just passed `revision`, would that get passed on?  Testing..

**Comment by marella** [comment]
Hi, thanks for letting me know. I'm currently out of station and have slow internet, so will look into it later.

**Comment by marella** [comment]
Added `revision` option for models on Hugging Face Hub in the latest version 0.2.23

**Comment by marella** [comment]
Hi @TheBloke, I'm working on making ctransformers fully compatible with 🤗 Transformers library. Would it be possible for you to include all the other files (config, json, tokenizer etc.) from original model repo in your GGML repos like the way you do for GPTQ?

**Comment by TheBloke** [comment]
Hey @marella yeah I can do that if it helps

But are you aware of the new GGUF that is very soon going to replace GGML?  It's likely going to be merged today. https://github.com/ggerganov/llama.cpp/pull/2398

One of the key features of the new GGUF format is that it is extensible and captures more data from the original model config.json and tokenizer files. If there's more data that you need, I would think the ideal solution would be to discuss with the team involved with GGUF about getting it added to the GGUF spec.  Then those extra files would not be needed.

I think it would be cleaner if any data needed was already in the GGUF file and there was no need for the original files, which do have the potential for causing confusion - making users think they are required for inference.

**Comment by TheBloke** [comment]
OK understood.   Sounds very interesting!

I wonder if that could even eventually lead to a proper Transformers GGML integration, like they just integrated GPTQ today (read more here: https://huggingface.co/blog/gptq-integration)

Are you OK if I provide those files in a separate folder?

Like I could make a folder called `hf-model-config` or a similar name.  Your code could check both the root path, and if not found, check that folder?

I'm just thinking of ways to minimise confusion and support requests - if they are in a separate folder hopefully people are less likely to think they might be required for them. I would also mention this in the README, for the 3% of people who read that :)

By the way I am planning to start including "How to use GGML models from Python code" sections in my READMEs.  I will use ctransformers for this, as it supports direct loading from HF which is really cool.  I will roll that out once your GGUF support is ready.

**Comment by marella** [comment]
> Are you OK if I provide those files in a separate folder?

Yes, you can name the folder `hf` to keep it short and simple. Please include all original files (`*.json`, `*.model`, `*.txt`, `*.py` etc.) except the original pytorch model files (`*.bin`). Thanks.

> By the way I am planning to start including "How to use GGML models from Python code" sections in my READMEs.

That would be great. I'm also thinking of adding ctransformers to hugging face hub libraries list so that it automatically shows `Use in CTransformers` button on top right similar to how it currently shows `Use in Transformers`.
