### ISSUE TITLE
Multi-threading concurrency, error reported 

### ISSUE THREAD

**Issue by sevenold** [marella/ctransformers#52]
https://colab.research.google.com/drive/1c6v2UUTcvrRtJBCxLk67KCWS_pd_2hCA

![image](https://github.com/marella/ctransformers/assets/41443157/6eaab3c1-d4cf-426c-a810-0d4ce08e171d)

segmentation fault (core dumped)

**Comment by marella** [comment]
ggml models are not thread safe so they shouldn't be called concurrently. Note that the model itself runs using multiple threads so it will use all available cores and there is no performance benefit of running multiple models at the same time. See https://github.com/marella/ctransformers/issues/38#issuecomment-1613627309
