### ISSUE TITLE
Failed to compile on linux ubuntu with gpu support

### ISSUE THREAD

**Issue by ParisNeo** [marella/ctransformers#53]
Hi there,

When I try to install with gpu support.
I set CT_CUBLAS to 1 then run:

pip install --upgrade --no-cache-dir ctransformers --no-binary ctransformers

But the compilation fails with this message:
Building wheels for collected packages: ctransformers
  Building wheel for ctransformers (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ctransformers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [120 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.9s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          /tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/sa226037/miniconda3/envs/lollms/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/sa226037/miniconda3/envs/lollms/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/sa226037/miniconda3/envs/lollms/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/sa226037/miniconda3/envs/lollms/bin/python -DPython_ROOT_DIR:PATH=/home/sa226037/miniconda3/envs/lollms -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/sa226037/miniconda3/envs/lollms/include/python3.10 -DPython3_EXECUTABLE:PATH=/home/sa226037/miniconda3/envs/lollms/bin/python -DPython3_ROOT_DIR:PATH=/home/sa226037/miniconda3/envs/lollms -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/sa226037/miniconda3/envs/lollms/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCT_CUBLAS=1 -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- CT_INSTRUCTIONS: avx2
      -- CT_CUBLAS: 1
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Check if compiler accepts -pthread
      -- Check if compiler accepts -pthread - yes
      -- Found Threads: TRUE
      -- x86 detected
      -- Found CUDAToolkit: /usr/include (found version "10.1.243")
      -- cuBLAS found
      -- The CUDA compiler identification is NVIDIA 10.1.243
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Configuring done (4.2s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/_skbuild/linux-x86_64-3.10/cmake-build
      [1/6] Building CUDA object CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o
      FAILED: CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o
      /usr/bin/nvcc  -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DGGML_USE_CUBLAS -DGGML_USE_K_QUANTS -DK_QUANTS_PER_ITERATION=2 -Dctransformers_EXPORTS -I/tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models -O3 -DNDEBUG -std=c++11 -Xcompiler=-fPIC -mfma -mavx2 -mf16c -mavx -Xcompiler -pthread -x cu -c /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/ggml/ggml-cuda.cu -o CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o && /usr/bin/nvcc  -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DGGML_USE_CUBLAS -DGGML_USE_K_QUANTS -DK_QUANTS_PER_ITERATION=2 -Dctransformers_EXPORTS -I/tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models -O3 -DNDEBUG -std=c++11 -Xcompiler=-fPIC -mfma -mavx2 -mf16c -mavx -Xcompiler -pthread -x cu -M /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/ggml/ggml-cuda.cu -MT CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o -o CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o.d
      nvcc fatal   : 'fma': expected a number
      [2/6] Building C object CMakeFiles/ctransformers.dir/models/ggml/k_quants.c.o
      [3/6] Building C object CMakeFiles/ctransformers.dir/models/ggml/ggml.c.o
      [4/6] Building CXX object CMakeFiles/ctransformers.dir/models/llm.cc.o
      In file included from /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llm.cc:9:
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llms/replit.cc: In function ‘std::pair<std::vector<int>, float> encode_word(const string&, const piece_map_t&)’:
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llms/replit.cc:66:37: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         66 |   for (int start_idx = 0; start_idx < word.length(); ++start_idx) {
            |                           ~~~~~~~~~~^~~~~~~~~~~~~~~
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llms/replit.cc:68:47: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         68 |     for (int end_idx = start_idx + 1; end_idx <= word.length(); ++end_idx) {
            |                                       ~~~~~~~~^~~~~~~~~~~~~~~~
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llms/replit.cc: In function ‘bool replit_tokenizer_load(replit_tokenizer&, std::istream&, int)’:
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llms/replit.cc:110:29: warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
        110 |   for (std::size_t i = 0; i < max_vocab_size; i++) {
            |                           ~~^~~~~~~~~~~~~~~~
      In file included from /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llms/falcon.cc:5,
                       from /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/llm.cc:13:
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/ggml/libfalcon.cpp: In function ‘bool falcon_eval_internal(falcon_context&, const llama_token*, int, int, int, const char*, int)’:
      /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/models/ggml/libfalcon.cpp:1539:20: warning: ‘cur’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       1539 |     cur = ggml_norm(ctx0, cur);
            |           ~~~~~~~~~^~~~~~~~~~~
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-2crcpvf0/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2
        Working directory:
          /tmp/pip-install-4in8aek4/ctransformers_9a9db3acd0744c699994bbf23b0103b2/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ctransformers

**Comment by linuxmagic-mp** [comment]
Similar error, Ubuntu Focal..  

CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers
```
      In file included from /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/models/llm.cc:9:
      /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/models/llms/replit.cc: In function ‘std::pair<std::vector<int>, float> encode_word(const string&, const piece_map_t&)’:
      /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/models/llms/replit.cc:66:37: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         66 |   for (int start_idx = 0; start_idx < word.length(); ++start_idx) {
            |                           ~~~~~~~~~~^~~~~~~~~~~~~~~
      /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/models/llms/replit.cc:68:47: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         68 |     for (int end_idx = start_idx + 1; end_idx <= word.length(); ++end_idx) {
            |                                       ~~~~~~~~^~~~~~~~~~~~~~~~
      /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/models/llms/replit.cc: In function ‘bool replit_tokenizer_load(replit_tokenizer&, std::istream&, int)’:
      /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/models/llms/replit.cc:110:29: warning: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
        110 |   for (std::size_t i = 0; i < max_vocab_size; i++) {
            |                           ~~^~~~~~~~~~~~~~~~
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-17ts2w37/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-17ts2w37/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-17ts2w37/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-17ts2w37/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361
        Working directory:
          /tmp/pip-install-x893y4ly/ctransformers_17a29425576d456b89a4d9491459e361/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
```

**Comment by marella** [comment]
@ParisNeo looks like you have a old version 10.1 of CUDA. Can you please try updating to latest version and try again. This looks related to https://github.com/ggerganov/llama.cpp/issues/1467

---

@linuxmagic-mp Can you also please try updating to latest CUDA version. If you are still getting error after updating, please run the install command with `--verbose` option and share its output:

```sh
CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers --verbose
```

**Comment by linuxmagic-mp** [comment]
Sorry, you are right I should have posted more information..
```
 nvidia-smi
Sun Jul 16 07:35:10 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090         Off| 00000000:41:00.0  On |                  Off |
|  0%   39C    P8               47W / 450W|    321MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1302      G   /usr/lib/xorg/Xorg                           59MiB |
|    0   N/A  N/A      1911      G   /usr/lib/xorg/Xorg                           93MiB |
|    0   N/A  N/A    228434      G   ...72105866,3531148907904441327,262144      117MiB |
+---------------------------------------------------------------------------------------+
```
After running in verbose, it showed.. 

```
  -- Found CUDAToolkit: /usr/include (found version "10.1.243")
  -- cuBLAS found
  -- The CUDA compiler identification is NVIDIA 10.1.243
...
  FAILED: CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o
  /usr/bin/nvcc  -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DGGML_USE_CUBLAS -DGGML_USE_K_QUANTS -DK_QUANTS_PER_ITERATION=2 -Dctransformers_EXPORTS -I/tmp/pip-install-29nw1hdq/ctransformers_cb52e739c653474990a0f85e8b04c63c/models -O3 -DNDEBUG -std=c++11 -Xcompiler=-fPIC -mfma -mavx2 -mf16c -mavx -Xcompiler -pthread -x cu -c /tmp/pip-install-29nw1hdq/ctransformers_cb52e739c653474990a0f85e8b04c63c/models/ggml/ggml-cuda.cu -o CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o && /usr/bin/nvcc  -DGGML_CUDA_DMMV_X=32 -DGGML_CUDA_DMMV_Y=1 -DGGML_USE_CUBLAS -DGGML_USE_K_QUANTS -DK_QUANTS_PER_ITERATION=2 -Dctransformers_EXPORTS -I/tmp/pip-install-29nw1hdq/ctransformers_cb52e739c653474990a0f85e8b04c63c/models -O3 -DNDEBUG -std=c++11 -Xcompiler=-fPIC -mfma -mavx2 -mf16c -mavx -Xcompiler -pthread -x cu -M /tmp/pip-install-29nw1hdq/ctransformers_cb52e739c653474990a0f85e8b04c63c/models/ggml/ggml-cuda.cu -MT CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o -o CMakeFiles/ctransformers.dir/models/ggml/ggml-cuda.cu.o.d
  nvcc fatal   : 'fma': expected a number
  [2/7] Building CXX object CMakeFiles/ctransformers.dir/models/ggml/cmpnct_unicode.cpp.o
  [3/7] Building C object CMakeFiles/ctransformers.dir/models/ggml/k_quants.c.o
  [4/7] Building C object CMakeFiles/ctransformers.dir/models/ggml/ggml.c.o
  [5/7] Building CXX object CMakeFiles/ctransformers.dir/models/llm.cc.o
...
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-o7neyao3/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 674, in setup
      cmkr.make(make_args, install_target=cmake_install_target, env=env)
    File "/tmp/pip-build-env-o7neyao3/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 697, in make
      self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
    File "/tmp/pip-build-env-o7neyao3/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 742, in make_impl
      raise SKBuildError(msg)
```

Grrr.. Also see that I have the 10.1 Cuda..
No chance of making it backwards compatible? ;)

**Comment by linuxmagic-mp** [comment]
#NVM @marella I see the new CUDA packages are available for Ubuntu Focal now (they were held back) However, might suggest that README be updated with those requirements (CUDA version and about the lack of prompts.)  Upgrading now.. will report back.

**Comment by linuxmagic-mp** [comment]
Small item, (I hate python ;) seems that find_package() keeps returning the wrong version, eg 10.1.243, while I have the newest installed ..
```
 NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2
``` 
I know it is probably some dumb trick to make it work, but was wondering.. you use find_package() and is that not now obsolete, given that CUDA is now a high level language? Could use a hint to speed things up .

**Comment by marella** [comment]
`find_package()` is related to CMake not Python. Try using `CMAKE_CUDA_COMPILER` option (specify path to CUDA 12.1 `nvcc` on your system):

```sh
CMAKE_ARGS="-DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc" CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers --verbose
```

**Comment by linuxmagic-mp** [comment]
Thanks for that hint, I had to forcibly set the path as well.. In order for it to find the new CUBLAS.
However, it still errors out. And  yes, understand that find_package is part of CMake (was grumbling about python, every time I upgrade the CUDA library, have to go double check a lot of the pip modules still work) But the documentation for CMake mentions that find_package() is now obsolete ... no matter.. 
```
  -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91")
  -- cuBLAS found
  -- The CUDA compiler identification is unknown
  CMake Error at /tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:603 (message):
    Failed to detect a default CUDA architecture.



    Compiler output:

  Call Stack (most recent call first):
    CMakeLists.txt:122 (enable_language)


  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "/tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 666, in setup
      env = cmkr.configure(
    File "/tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 357, in configure
      raise SKBuildError(msg)

  An error occurred while configuring with CMake.
    Command:
      /tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/cmake/data/bin/cmake /tmp/pip-install-98ed7z0x/ctransformers_de52fd30dac54c25bbf2efe2781ab74a -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-98ed7z0x/ctransformers_de52fd30dac54c25bbf2efe2781ab74a/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-3j69aw8w/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc -DCT_CUBLAS=1 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc
    Source directory:
      /tmp/pip-install-98ed7z0x/ctransformers_de52fd30dac54c25bbf2efe2781ab74a
    Working directory:
      /tmp/pip-install-98ed7z0x/ctransformers_de52fd30dac54c25bbf2efe2781ab74a/_skbuild/linux-x86_64-3.10/cmake-build
  Please see CMake's output for more information.

  error: subprocess-exited-with-error
  
  × Building wheel for ctransformers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```
Can't find a default architecture now :( But sure you understand what is happening.

**Comment by linuxmagic-mp** [comment]
As I said, you probably know more than me about the CMake stuff, but wondering about:

```
set_property(TARGET ctransformers PROPERTY CUDA_ARCHITECTURES OFF)
```

Since you use CMake 3.26.xx > 3.24.. 
It suggests.. 
```
set_property(TARGET tgt PROPERTY CUDA_ARCHITECTURES native)
```

But, like I said.. I am sure you know better how to solve the problem in your package.  Do you need any other information from me about my environment?

**Comment by marella** [comment]
I added precompiled libraries for CUDA 12 in the latest version 0.2.13

Can you please try installing it using:

```sh
pip uninstall ctransformers --yes # uninstall if already installed
pip install 'ctransformers>=0.2.13'
```

and then run by specifying `gpu_layers`:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/LLaMa-7B-GGML", gpu_layers=50)
```

Please let me know if this works.

**Comment by linuxmagic-mp** [comment]
I am afraid the same issue.. 

Just to be sure, ran with all the same options as before

```
PATH=/usr/local/cuda/bin${PATH:+:${PATH}} CMAKE_ARGS="-DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.1/bin/nvcc" CT_CUBLAS=1 python3 -m pip install 'ctransformers>=0.2.13' --no-binary ctransformers --verbose
```
error (clipped)
```
  -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91")
  -- cuBLAS found
  -- The CUDA compiler identification is unknown
  CMake Error at /tmp/pip-build-env-z_i01yqv/overlay/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:603 (message):
    Failed to detect a default CUDA architecture.
```

**Comment by ParisNeo** [comment]
I think we may need to find a way to have a stable install that doesn't require too much tinkering.
We are geeks, we can afford playing around and recompiling with different flags.

but final users are most of the time ignorant about all this and just need to have a tool that they install in oneclick.

In lollms (Lord Of Large Language Models), I have developed an install script that installs conda, cuda toolkit and all needed libraries on linux, windows and macos, and it starts the ui easily.

But when it comes to installing bindings (like ctransformer and autogptq and gpt4all etc) it is a pain to code a script that installs it without it breaking on some configurations. the fact that hardware changes is painful.

**Comment by marella** [comment]
@linuxmagic-mp you don't have to specify any extra options as I'm providing precompiled binaries for CUDA 12. You can just install normally using:

```sh
pip install 'ctransformers>=0.2.13'
```

and then run by specifying `gpu_layers`:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/LLaMa-7B-GGML", gpu_layers=50)
```

---

@ParisNeo if above works, at least for CUDA 12, users will no longer have to build it on their systems and just use the precompiled binaries.

**Comment by linuxmagic-mp** [comment]
That works.. (At least the install), but FYI, loading a local ggml model. Howev,er it does balk trying to run.. 

```
llm = AutoModelForCausalLM.from_pretrained('/home/michael/models/falcon-40b-ggml/ggml-model--f32.bin', model_type='Falcon', gpu_layers=5)
```

```
Model type 'Falcon' is not supported.
Traceback (most recent call last):
  File "/home/michael/git/lollms-webui/remove_me.py", line 3, in <module>
    llm = AutoModelForCausalLM.from_pretrained('/home/michael/models/falcon-40b-ggml/ggml-model--f32.bin', model_type='Falcon', gpu_layers=5)
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/hub.py", line 157, in from_pretrained
    return LLM(
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/llm.py", line 214, in __init__
    raise RuntimeError(
RuntimeError: Failed to create LLM 'Falcon' from '/home/michael/models/falcon-40b-ggml/ggml-model--f32.bin'.
```

**Comment by linuxmagic-mp** [comment]
Grr.. 'falcon' is case sensitive.. for model_type. Thanks for your help. You can close this ticket for now, any other problems should go under a different ticket.

**Comment by marella** [comment]
@ParisNeo hope this resolves the issue for you as well?

**Comment by ParisNeo** [comment]
Well, I ended up creating a self contained install for noobs. But this is good, I will update everything to use this new version with cuda 12
