### ISSUE TITLE
Please assist using langchain RetrievalQA

### ISSUE THREAD

**Issue by garth-waters** [marella/ctransformers#54]
Hi
I am need of some assistance please:
I am using AutoModelForCausalLM.from_pretrained so that I can use GPU,
I am trying to use langchains RetrievalQA to query pdfs.
Do you have some code that can assist please?

If I use RetrievalQA.from_llm then I get:
ValidationError: 1 validation error for LLMChain
llm
  value is not a valid dict (type=type_error.dict)

Many Thanks
Garth Waters

**Comment by marella** [comment]
Hi, in LangChain, you shouldn't use `AutoModelForCausalLM.from_pretrained`. You should use `CTransformers` class to create llm object:

```py
from langchain.llms import CTransformers

llm = CTransformers(model='...', model_type='...')

qa = RetrievalQA.from_chain_type(llm=llm, ...)
```

See [LangChain docs](https://python.langchain.com/docs/ecosystem/integrations/ctransformers).

Also see:

- https://github.com/marella/chatdocs
- https://github.com/marella/chatdocs/blob/2927aa21ab12f815dbad75e5340e57b22daad3f4/chatdocs/llms.py#L70-L73
- https://github.com/marella/chatdocs/blob/main/chatdocs/chains.py
