### ISSUE TITLE
RedPajama support

### ISSUE THREAD

**Issue by NeonBohdan** [marella/ctransformers#6]
Please, very good and small model
https://huggingface.co/togethercomputer/RedPajama-INCITE-Chat-3B-v1

**Comment by marella** [comment]
Hi, I think it should work with `model_type=gpt_neox`. You can convert the model to ggml format by following the instructions [here](https://github.com/ggerganov/ggml/tree/master/examples/gpt-neox#usage).
Please let me know if it works.

**Comment by NeonBohdan** [comment]
Thanks, they changed arch a bit
They made a [fork](https://github.com/togethercomputer/redpajama.cpp) for conversion to work

**Comment by NeonBohdan** [comment]
Here is the exact [description](https://github.com/togethercomputer/redpajama.cpp/tree/master/examples/redpajama#ackonwledgement)

**Comment by NeonBohdan** [comment]
Sorry my bad 
After [this PR](https://github.com/ggerganov/ggml/pull/139) RedPajama works
I just used wrong [model](https://huggingface.co/keldenl/RedPajama-INCITE-Chat-3B-v1-GGML) to try it and run
Converting by myself helped

Great project, this is what GGML needs
