### ISSUE TITLE
Issues with ctransformers_llm_create and Falcon-40b model

### ISSUE THREAD

**Issue by linuxmagic-mp** [marella/ctransformers#60]
Calling it from LolLMS Webgui, and get the error...

error loading model: unknown (magic, version) combination: 04034b50, 08080000; is this really a GGML file?

WizardLM-Uncensored-Falcon-40b/training_args.bin is passed in..  falcon as type

Now, this directory had the original model, as well as the GGML bin, as well as a quantized version.. 

I see the error is generated from .. 

models/ggml/llama.cpp Line 502

What I am confused with, is why it is there at all given there is no falcon models there.
I don't see in the code the decision tree, to load falcon instead of llama?

**Comment by linuxmagic-mp** [comment]
For the record, ran debug through the python code, confirm that 'falcon' is passed correctly all the way to lib.ctransformers_llm_create(), but still can't figure out why it is calling the load file from llama.cpp, and not the falcon.cpp, reached the end of my debugging ability, without patching the c code.. I must be missing something obvious I am missing.

**Comment by linuxmagic-mp** [comment]
And a reminder, it does work calling it as:
```
from ctransformers import AutoModelForCausalLM
llm = AutoModelForCausalLM.from_pretrained('/home/michael/models//WizardLM-Uncensored-Falcon-40b/ggml-model-falcon-40b-wizardlm-f32.bin', model_type='falcon', gpu_layers=50)
print(llm('AI is going to'))
```
```
falcon.cpp: fallback for old file format. Loading BPE merges from tokenizer.json
falcon.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
falcon_model_load_internal: INFO: not enough VRAM to offload layer 17 (missing 139881 MB)
falcon_model_load_internal: INFO: 6 layers will be offloaded to GPU (layers 11 to 17)
 change the way we work, but it’s not as simple as just replacing humans with machines. In fact, AI can actually enhance our abilities and make us more productive.
Here are five ways AI can help you be more efficient in your job:
1. Automate repetitive tasks
One of the biggest benefits of AI is that it can automate repetitive tasks, freeing up time for employees to focus on more complex tasks that require human judgment and creativity. For example, chatbots can handle customer service inquiries, freeing up customer service representatives to handle more complicated issues.
2. Analyze data faster
AI can analyze large amounts of data much faster than humans, allowing you to make better decisions based on insights from the data. This can be particularly useful in industries like finance or healthcare where there is a lot of data to process and analyze.
3. Improve decision-making
In addition to analyzing data, AI can also help improve decision-making by providing recommendations based on that data. For example, AI tools can analyze customer behavior and recommend personalized marketing campaigns for individual customers.
4. Streamline processes
AI can streamline business processes by automating routine tasks like scheduling appointments or sending out invoices. This can save time and reduce the risk of errors caused by manual data entry

Message from syslogd@localhost at Jul 22 11:59:34 ...
 kernel:[532498.456019] watchdog: BUG: soft lockup - CPU#21 stuck for 22s! [python3:154011]

```

So it has to be something in the code base when called via load_library() && lib.ctransformers_llm_create() , still confusing me..

**Comment by linuxmagic-mp** [comment]
In class LLM, the model path is /home/michael/models/WizardLM-Uncensored-Falcon-40b/training_args, which of course is the training_args from the original model, before conversion to the GGML. 
```
self._llm = self._lib.ctransformers_llm_create(
            model_path.encode(),
            model_type.encode(),
            config.context_length,
            config.gpu_layers,
        )
```
This 'should' run 
```
} else if (type == "falcon") {
    llm = new falcon_llm;
```
in the llm.cc helper I assume, but really confused as how the actual GGML file is specified, just based on the training_args.bin.  Sorry, really want to help, but in over my head on this one, I am more familiar with it needing both the file path, and file name.  Anything I can do to help, let me know..

**Comment by linuxmagic-mp** [comment]
```
LLM* ctransformers_llm_create(const char* model_path, const char* model_type,
                              const int context_length, const int gpu_layers) {
```
Only way to make this properly work with multiple versions of the same model in the model_path, is to be able to pass in model as well as model_path.  ?

**Comment by linuxmagic-mp** [comment]
Okay, it looks like this is an issue where AutoModelForCausalLM is called with just a model_path, and the tries to perform _find_model_path_from_dir.  If this case, it looks for anything ending with a .bin. It's no issue if filename is passed, but when it isnt' it takes any file that ends with .bin however, that can be non-llm files as well. So, if it finds several files, it assumes that the first file it found is the model.  In my case, the first file it finds is training_args.bin.  And of course that will fail later on.  Suggest that if JUST the model_path is provided, and multiple .bin files satisfy the criteria, throw an error failing to load the model, and let them know to pass in a file name. 

Please fix...
```
def _find_model_path_from_dir(
        cls,
        path: str,
        filename: Optional[str] = None,
    ) -> str:
        path = Path(path).resolve()
        if filename:
            file = (path / filename).resolve()
            if not file.is_file():
                raise ValueError(f"Model file '{filename}' not found in '{path}'")
            return str(file)

        files = [
            (f.stat().st_size, f)
            for f in path.iterdir()
            if f.is_file() and f.name.endswith(".bin")
        ]
        if not files:
            raise ValueError(f"No model file found in directory '{path}'")
        file = min(files)[1]
        return str(file.resolve())

```

**Comment by marella** [comment]
The model path can be path to a directory or model file. If it is path to a directory, then it will look for `.bin` files in that directory. If there are multiple `.bin` files in a directory, then it will pick the smallest file.

To use a specific file you can just pass the path to the model file directly or use the `model_file` paramater. For example, if a directory `falcon-7b-ggml` has two files: `model-q4_0.bin` (small size), `model-q4_1.bin` (large size) and you want to use `model-q4_1.bin`, then you can use one of the following:

```py
llm = AutoModelForCausalLM.from_pretrained("/path/to/falcon-7b-ggml/model-q4_1.bin")
# or
llm = AutoModelForCausalLM.from_pretrained("/path/to/falcon-7b-ggml", model_file="model-q4_1.bin")
```

`model_file` can also be used with Hugging Face repos:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/falcon-7b-instruct-GGML", model_file="falcon-7b-instruct.ggccv1.q4_1.bin")
```

> Suggest that if JUST the model_path is provided, and multiple .bin files satisfy the criteria, throw an error failing to load the model, and let them know to pass in a file name.

It used to throw error earlier in older versions, but I changed it to simplify using it with multiple quantized files. For example, it can be used with HF repos containing multiple quantized files without specifying any filenames:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/falcon-7b-instruct-GGML")
```

**Comment by linuxmagic-mp** [comment]
I should probably close this issue, it isnt' really a ctransformers issue at this point. Eg, the calling program is at fault for not specifying the filename (Lollms-WebUI)  Working through it.. :(
