### ISSUE TITLE
llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024 llama_init_from_file: failed to load model

### ISSUE THREAD

**Issue by vmajor** [marella/ctransformers#62]
This error occurs with quantized 70B model that works with the latest current master branch of llama.cpp

```
llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_init_from_file: failed to load model
```

I am guessing that you would just need to update the PyPi package. Will try to build from source in the meantime.

**Comment by vmajor** [comment]
...actually fixing this is well beyond my skill level, but it is indeed related to the newness of the 70B model handling. Quantization changed: 
https://github.com/ggerganov/llama.cpp/pull/2276

**Comment by klosax** [comment]
@vmajor 

Did you use the `--gqa 8` parameter, which is needed for using the 70b model?

**Comment by klosax** [comment]
No sorry, my mistake. You will need the newest master from llama.cpp and it needs the `-gqa 8` parameter for 70b models.

**Comment by vmajor** [comment]
...and no, cannot set up the LLM instance, invalid argument. I have llama.cpp working, but that does not help as I need python bindings. I am waiting for llama-cpp-python to update, otherwise I can build the required .so by pulling the working llama.cpp and building from source.

Cannot do the same with ctransformers as it is written in c++ and I do not speak that language

**Comment by marella** [comment]
Added support for LLaMA 2 70B models in the latest version 0.2.15

Since `gqa` param appears to be a [temporary](https://github.com/ggerganov/llama.cpp/blob/8a88e5855c3b93024be0f93290b01a4206b65b38/llama.cpp#L1051) solution, I haven't added it as a config parameter. In order to use 70B models, the model path or repo name must contain the word `70B`. For example, `llama-2-70b.bin`, `llama-2-70b/ggml-model.bin`, `TheBloke/Llama-2-70B-GGML` etc.

@TheBloke models should work out of the box without any additional configuration:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-70B-GGML")
```

**Comment by TheBloke** [comment]
That won't work with https://huggingface.co/TheBloke/StableBeluga2-GGML unless I rename it

**Comment by TheBloke** [comment]
I renamed StableBeluga2 to StableBeluga2-70B

**Comment by viktor-ferenczi** [comment]
The ggml loader relies on this horrible hack:
```
std::regex pattern_70b(R"((\b|_)70b(\b|_))", std::regex_constants::icase);
```

There seem to be no way to set `n_gqa=8` while using ctransformers from Python code.

Any solution for GGML other than waiting for GGUF support?

**Comment by marella** [comment]
GGUF support is added in 0.2.24

`n_gqa` was a temporary parameter so I didn't add it. It is now no longer supported in llama.cpp
For ggml models add `70b` to file name as mentioned [above](https://github.com/marella/ctransformers/issues/62#issuecomment-1656479877).
