### ISSUE TITLE
gpu_layers not working

### ISSUE THREAD

**Issue by yapnel** [marella/ctransformers#63]
I'm executing the below code specifying the gpu_layers and it is throwing the below error and i can confirm the path to the DLL exists. 

FileNotFoundError: Could not find module 'C:\Temp\retrievalaugmentedgeneration\.venv\Lib\site-packages\ctransformers\lib\cuda\ctransformers.dll' (or one of its dependencies). Try using the full path with constructor syntax.

`from ctransformers import AutoModelForCausalLM

conf={'temperature':0.5, 'gpu_layers':32}

llm = AutoModelForCausalLM.from_pretrained(model_file='llama-2-7b-chat.ggmlv3.q4_1.bin', model_type='llama', 
model_path_or_repo_id='./models/', local_files_only=True, **conf)

response = llm('AI is going to')

print(response)`
[err.log](https://github.com/marella/ctransformers/files/12149552/err.log)
[err.log](https://github.com/marella/ctransformers/files/12149553/err.log)

**Comment by marella** [comment]
Can you please try running it without `gpu_layers` and see if it works. This error can occur when one of the dependencies such as CUDA 12 are missing or unable to find it.

**Comment by yapnel** [comment]
Newbie error here. I've got an Intel GPU instead of NVidia, maybe that's the reason for the error message. Thanks for looking into my query.
