### ISSUE TITLE
Custom fine tuned model conversion to ggml and using through CTransformer python interface?

### ISSUE THREAD

**Issue by Anindyadeep** [marella/ctransformers#67]
The CTransformers repo is amazing and is doing an awesome work. However, I have some doubts. Currently so far, what I have understood (please correct me if I am wrong) that, we can use any ggml models (having support for both CPU/GPU) if we have a `ggml-model.bin` kind of a file? 

If so, then I have two questions, which I am finding difficult to get proper answer

1. So, if there is any `ggml-model.bin` file of supported model architecture available, then can I load that through CTransformers?

2. I have a pretrained `Llama 7B` model and now I fine tuned the model using `4 bit quantization` and now I want to convert this fine tuned model with my adapter weights into ggml format so that I can load that using CTransformers?

**Comment by faustusdotbe** [comment]
For 2,  how did you do it?

It's pretty straightforward to do using llama.cpp https://github.com/ggerganov/llama.cpp#prepare-data--run

**Comment by Anindyadeep** [comment]
@faustusdotbe 
If I am not wrong you might be intersted in knowing, how did I fine tuned it, then here is the code showing the same https://github.com/Anindyadeep/LLMFineTunerInference

**Comment by faustusdotbe** [comment]
If you already have a fine-tuned model then it's pretty straightforward to quantize using llama.cpp as linked

**Comment by Anindyadeep** [comment]
I see, I was a bit reluctant to do so, so I thought if it can be done through CTransformer's interface.

**Comment by marella** [comment]
1. Yes. Most of the ggml models available [here](https://huggingface.co/TheBloke) can be loaded using ctransformers.
2. No, it doesn't provide scripts for converting to ggml. As mentioned by faustusdotbe, you will have to use the scripts in [llama.cpp](https://github.com/ggerganov/llama.cpp) repo. For non-llama models, scripts are in [ggml](https://github.com/ggerganov/ggml/tree/master/examples) repo.
