### ISSUE TITLE
Best backend yet!

### ISSUE THREAD

**Issue by ParisNeo** [marella/ctransformers#7]
Thanks for this cool library. I have integrated it into my gpt4All-ui 
![image](https://github.com/marella/ctransformers/assets/827993/45acc1fe-f26c-41c5-bd97-8aa3b8f20ccc)

If you want, please come to the discord channel. You are welcome to suggest ideas or discuss the future of all of this stuff:
https://discord.gg/FAfwMshF

And to test the tool, you can find it here:
[https://github.com/nomic-ai/gpt4all-ui/releases/tag/v0.0.8](https://github.com/nomic-ai/gpt4all-ui/releases/tag/v0.0.8)

**Comment by marella** [comment]
Thanks. Joined the discord server.
