### ISSUE TITLE
Is there a way to release GPU memory occupied by previous constructed LLM class?

### ISSUE THREAD

**Issue by lppllppl920** [marella/ctransformers#72]
I don't seem to be able to release the GPU memory occupied by the previous LLM object even though I use python del operation on it. Is there an official way of doing that that is supported by ctransformers?

**Comment by marella** [comment]
`del llm` should free the memory. I just tested on Google Colab, GPU memory is freed after running `del llm`.
Can you try loading a model, deleting and loading again. If it is not freeing up, you will see twice the memory usage:

```py
llm = AutoModelForCausalLM.from_pretrained(..., gpu_layers=...)
del llm
llm = AutoModelForCausalLM.from_pretrained(..., gpu_layers=...)
```

**Comment by lppllppl920** [comment]
```
if __name__ == "__main__":
    import os
    os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    config = AutoConfig.from_pretrained(
       "/path/to/ggllm.cpp/model",
        stop="<|endoftext|>",
        threads=1,
        gpu_layers=24,
        batch_size=512,
        stream=True,
        last_n_tokens=0,
        seed=-1,
    )
    while True:
        model = AutoModelForCausalLM.from_pretrained(
                "/path/to/ggllm.cpp/model",
                model_type="falcon",
                config=config,
            )
        del model
```


The code above doesn't seem to release GPU memory everytime I call `del model`. The GPU memory just continuously increase until OOM.

**Comment by lppllppl920** [comment]
version 0.2.18 seems to have fixed this issue. Was testing it with 0.2.16 before.
