### ISSUE TITLE
getting odd LLM results, advice for newbies?

### ISSUE THREAD

**Issue by bbartling** [marella/ctransformers#74]
Hi,

Great job on the repo, I am trying the Collab notebook code like this below which pops up a chat interface:

```
from ctransformers import AutoModelForCausalLM
from IPython.display import display, clear_output
import ipywidgets as widgets

# Output widget for AI response
output = widgets.Output()
display(output)

llm = AutoModelForCausalLM.from_pretrained("TheBloke/LLaMa-7B-GGML",
                                           temperature=0,
                                           gpu_layers=50)

while True:
    user_input = input("Human: ")
    if output:
      print(f"AI: {llm(user_input)})")
```

I asked the LLM 3 questions, denoted by `Human:` below and the LLM response is `AI:`. One question to make a hello world Flask app, another question to make an LLM rest API server, and then 200 words on what sick building syndrome is. It seemed to do well in the sick building response but notice in the code creation a `Fetching files`, just curious what this is? Just curious about any tips to get any better results! Great job on the GPU support!

> Fetching 1 files: 100%
> 1/1 [00:00<00:00, 69.71it/s]
> Fetching 1 files: 100%
> 1/1 [00:00<00:00, 55.18it/s]
> Human: write a hello world flask app
> AI: 
> write a hello world flask app - 100% working
> Write a simple Flask application that greets the user with "Hello, world" and then exits.
> This is an exercise in learning how to use the Python programming language in the context of the Flask framework for building web applications.
> The following are the steps you will need to take:
> 1. Install the latest version of the Python development environment (the one that comes with your operating system).
> 2. Create a directory, and then cd into it.
> 3. Run the following command in the terminal:
> python -m flask runserver 8000
> This will create an application at http://localhost:8000/.
> 4. Open up a web browser (e.g., Chrome) and go to http://localhost:8000/
> 5. You should see something like the following:
> 6. Now, type in your name, and press enter.
> 7. Press Ctrl + D to exit.
> 8. Run the following command in the terminal:
> This will create an application at http://localhost:8000/
> 9. Open up a web browser (e.g., Chrome) and)
> Human: write a flask app that is a REST API server for an LLM. The app will take in text data on a POST, process the data through the LLM, and return the LLM's response as JSON
> AI: .
> The project should be 100% written in Python using Flask. I can provide the source code of the LLM if needed.
> Hi, I am an experienced python developer with 2 years experience in python development. I have already done many projects like this. Please contact me for more details.)
> Human: in 200 words write what sick building syndrome is
> AI: 
> Sick Building Syndrome is a condition that occurs in the workplace. It is caused by the air quality, temperature, humidity, lighting, ventilation, and other factors. The symptoms are headaches, dizziness, fatigue, nausea, cough, sore throat, dry mouth, watery eyes, nosebleeds, nasal congestion, sinusitis, asthma, breathlessness, chest tightness, phlegm, and other respiratory problems.
> The cause of Sick Building Syndrome is the air quality in the workplace. The symptoms are headaches, dizziness, fatigue, nausea, cough, sore throat, dry mouth, watery eyes, nosebleeds, nasal congestion, sinusitis, asthma, breathlessness, chest tightness, phlegm, and other respiratory problems.
> The cause of Sick Building Syndrome is the air quality in the workplace. The symptoms are headaches, dizziness, fatigue, nausea, cough, sore throat, dry mouth, watery eyes, noseble)

**Comment by talhaanwarch** [comment]
may be you can look into my repo
https://github.com/talhaanwarch/streamlit-llama/blob/main/app.py

**Comment by bbartling** [comment]
I didn't realize that the Bloke had so many models. Would you have any
advice for more advanced model logic and reasoning type of questions I am
asking the LLM?

https://huggingface.co/TheBloke

On H20 GPT, my questions are answered just fine on full blown 70b Llama and
others but the compressed models I definitely have some issues.

This is really cool IMHO for testing a lot of model results at the same
time.

https://gpt.h2o.ai/

Thanks!
