### ISSUE TITLE
install from source with CUDA support?

### ISSUE THREAD

**Issue by lppllppl920** [marella/ctransformers#82]
I see in the README that `pip install ctransformers[cuda]` will be able to install ctransformers with CUDA support. However, there is no instruction on how installing from source would have CUDA support. Is there a way to do that?

**Comment by marella** [comment]
If you are installing from repo, you can use:

```sh
CT_CUBLAS=1 pip install git+https://github.com/marella/ctransformers
```

If you want to install from your local clone of repo:

```sh
CT_CUBLAS=1 pip install /path/to/ctransformers
```
