### ISSUE TITLE
Config for tokens

### ISSUE THREAD

**Issue by bbartling** [marella/ctransformers#83]
In the config, what is most similar to when using Chat GPT backend you have to state max number of tokens to use? Do you have to worry about an error if you go over the number of tokens on your question to the LLM?

Can someone also help me understand `top_k` and `top_p` params?

- top_k
- top_p 
- temperature 
- repetition_penalty 
- last_n_tokens
- seed
- max_new_tokens
- stop 
- stream 
- reset
- batch_size
- threads
- context_length 
- gpu_layers

**Comment by marella** [comment]
If you are looking for limit on number of tokens in prompt, it is controlled by `context_length` which is model dependent. If you go over the limit, it will simply ignore the first few tokens that are outside the limit.
If you are looking for max number of tokens to generate, it is `max_new_tokens`
See [this](https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md#top-k-sampling) for `top_k`, `top_p` explanation.
