### ISSUE TITLE
Cuda runtime incompatibility in Colab

### ISSUE THREAD

**Issue by RonanKMcGovern** [marella/ctransformers#84]
I'm using the sample Colab script provided, adapted to specify the model type and also offload to the gpu:
```
llm = AutoModelForCausalLM.from_pretrained(
    "Trelis/Llama-2-7b-chat-hf-function-calling-GGML",
    model_type='llama',
    # gpu_layers=32
    )
```

The error I'm seeing is:
```
OSError                                   Traceback (most recent call last)
[<ipython-input-12-63b926862e73>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = AutoModelForCausalLM.from_pretrained(
      2     'Trelis/Llama-2-7b-chat-hf-function-calling-GGML',
      3     model_type='llama',
      4     gpu_layers=32)

3 frames
[/usr/lib/python3.10/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

OSError: libcudart.so.12: cannot open shared object file: No such file or directory
```

btw the colab cuda version is:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by marella** [comment]
You should also install the compatible CUDA runtime libraries using:

```py
pip install ctransformers[cuda]
```

See [example](https://colab.research.google.com/drive/1Ihn7iPCYiqlTotpkqa1tOhUIpJBrJ1Tp) in Colab.

**Comment by RonanKMcGovern** [comment]
Appreciate the quick response, that fix worked.

fwiw (and I may be misunderstanding), Llama 2 has 32 layers (although I assume setting 50 for inference just means all layers are offloaded to the GPU).

**Comment by marella** [comment]
Yes, it is ok to set it to a number higher than the actual number of layers. It is actually better to set it to a higher number so that non-repeating layers and kv cache are also offloaded to GPU.

**Comment by RonanKMcGovern** [comment]
oh, that's a great tip, thanks! that likely will allow higher toks (cos I was wondering why ggml was slower than gptq).

**Comment by AayushSameerShah** [comment]
Is there any way to automatically set all layers to GPU? Instead of remembering how many or setting too high a number like 9999 to make sure all layers are set on the GPU?
