### ISSUE TITLE
number of gpu_layers

### ISSUE THREAD

**Issue by aliakyurek** [marella/ctransformers#93]
What is the maximum number of gpu layers?
Does it depend on model or gpu card? How can we learn the maximum number of it?

**Comment by marella** [comment]
Yes, it depends on the model and GPU memory . If a model has 32 layers and if you specify `gpu_layers=50` or `gpu_layers=100`, it will only offload 32 layers. So you can just start with a large number say 100 and reduce (binary search) it if you are getting out of memory errors.
