### ISSUE TITLE
In the future will it require huggingface credentials to load the model?

### ISSUE THREAD

**Issue by Revanth-guduru-balaji** [marella/ctransformers#94]
Is there a way to have the model file llama-2-70b-chat.ggmlv3.q4_K_S.bin in local  and load  it and able to use Ctransformers. Kindly share some snippets of loading which package to use . Because I dont want to download again and again.

**Comment by marella** [comment]
It doesn't require any credentials to load publicly available models. Downloaded models will be cached locally so it will not download again. If you want to load a specific file specify using `model_file`:

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-70B-Chat-GGML", model_file="llama-2-70b-chat.ggmlv3.q4_K_S.bin")
```

or you can just manually download the model file and use it as:

```py
llm = AutoModelForCausalLM.from_pretrained("/path/to/llama-2-70b-chat.ggmlv3.q4_K_S.bin", model_type="llama")
```

**Comment by Revanth-guduru-balaji** [comment]
Thanks, is there a way to use GPU. How to do changes in code

**Comment by Revanth-guduru-balaji** [comment]
> It doesn't require any credentials to load publicly available models. Downloaded models will be cached locally so it will not download again. If you want to load a specific file specify using `model_file`:
> 
> ```python
> llm = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-70B-Chat-GGML", model_file="llama-2-70b-chat.ggmlv3.q4_K_S.bin")
> ```
> 
> or you can just manually download the model file and use it as:
> 
> ```python
> llm = AutoModelForCausalLM.from_pretrained("/path/to/llama-2-70b-chat.ggmlv3.q4_K_S.bin", model_type="llama")
> ```

Thanks, is there a way to use GPU. How to do changes in code

**Comment by marella** [comment]
For GPU, see [README](https://github.com/marella/ctransformers#gpu) and [example](https://colab.research.google.com/drive/1Ihn7iPCYiqlTotpkqa1tOhUIpJBrJ1Tp) in Colab.
