### ISSUE TITLE
 Is support available for TheBloke/Llama-2-70B-Chat-GGML

### ISSUE THREAD

**Issue by Revanth-guduru-balaji** [marella/ctransformers#96]
It is taking long time to answer in google colab T4 GPU .

from ctransformers import AutoModelForCausalLM
llm = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-70B-Chat-GGML")
llm("what is ai")

**Comment by marella** [comment]
Google Colab only provides around 16GB GPU memory which is not enough to load 70B models. So you should try with smaller models.
Also when using GPU you should specify `gpu_layers`. See [example](https://colab.research.google.com/drive/1Ihn7iPCYiqlTotpkqa1tOhUIpJBrJ1Tp).
